import type { EmojiCombo } from '../types/combo';

export const POPULAR_COMBOS: EmojiCombo[] = [
  // ZWJ Sequences
  {
    id: 'family',
    display: '👨‍👩‍👧‍👦',
    description: 'Family',
    components: ['👨', '👩', '👧', '👦'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },
  {
    id: 'man-technologist',
    display: '👨‍💻',
    description: 'Man Technologist',
    components: ['👨', '💻'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },
  {
    id: 'woman-astronaut',
    display: '👩‍🚀',
    description: 'Woman Astronaut',
    components: ['👩', '🚀'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },
  {
    id: 'rainbow-flag',
    display: '🏳️‍🌈',
    description: 'Rainbow Flag',
    components: ['🏳️', '🌈'],
    type: 'zwj',
    category: 'flags',
    popular: true,
  },
  {
    id: 'man-cook',
    display: '👨‍🍳',
    description: 'Man Cook',
    components: ['👨', '🍳'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },
  {
    id: 'woman-doctor',
    display: '👩‍⚕️',
    description: 'Woman Doctor',
    components: ['👩', '⚕️'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },
  {
    id: 'man-teacher',
    display: '👨‍🏫',
    description: 'Man Teacher',
    components: ['👨', '🏫'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },
  {
    id: 'woman-artist',
    display: '👩‍🎨',
    description: 'Woman Artist',
    components: ['👩', '🎨'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },
  {
    id: 'man-farmer',
    display: '👨‍🌾',
    description: 'Man Farmer',
    components: ['👨', '🌾'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },
  {
    id: 'woman-scientist',
    display: '👩‍🔬',
    description: 'Woman Scientist',
    components: ['👩', '🔬'],
    type: 'zwj',
    category: 'people',
    popular: true,
  },

  // Popular Pairs
  {
    id: 'thumbs-heart',
    display: '👍❤️',
    description: 'Approval + Love',
    components: ['👍', '❤️'],
    type: 'pair',
    category: 'gestures',
    popular: true,
  },
  {
    id: 'fire-perfect',
    display: '🔥💯',
    description: 'Fire + Perfect',
    components: ['🔥', '💯'],
    type: 'pair',
    category: 'symbols',
    popular: true,
  },
  {
    id: 'laugh-dead',
    display: '😂💀',
    description: 'Laughing + Dead',
    components: ['😂', '💀'],
    type: 'pair',
    category: 'smileys',
    popular: true,
  },
  {
    id: 'rocket-star',
    display: '🚀⭐',
    description: 'Success + Achievement',
    components: ['🚀', '⭐'],
    type: 'pair',
    category: 'symbols',
    popular: true,
  },
  {
    id: 'heart-angel',
    display: '❤️😇',
    description: 'Love + Pure',
    components: ['❤️', '😇'],
    type: 'pair',
    category: 'smileys',
    popular: true,
  },
  {
    id: 'party-celebration',
    display: '🎉🎊',
    description: 'Party + Celebration',
    components: ['🎉', '🎊'],
    type: 'pair',
    category: 'activities',
    popular: true,
  },
  {
    id: 'beer-cheers',
    display: '🍺🍻',
    description: 'Drinking + Cheers',
    components: ['🍺', '🍻'],
    type: 'pair',
    category: 'food',
    popular: true,
  },
  {
    id: 'coffee-morning',
    display: '☕🌅',
    description: 'Coffee + Morning',
    components: ['☕', '🌅'],
    type: 'pair',
    category: 'food',
    popular: true,
  },
];

export const SHORTCUTS_DATA = [
  { key: 'Ctrl + K', action: 'focusSearch', description: 'Focus search bar' },
  {
    key: 'Esc',
    action: 'clearSearch',
    description: 'Clear search / Close modal',
  },
  { key: 'Arrow Keys', action: 'navigate', description: 'Navigate emoji grid' },
  { key: 'Enter / Space', action: 'copy', description: 'Copy selected emoji' },
  { key: '?', action: 'help', description: 'Show shortcuts help' },
  { key: '1-9', action: 'category', description: 'Quick switch categories' },
  { key: 'Ctrl + R', action: 'reset', description: 'Reset filters' },
  {
    key: 'Tab',
    action: 'navigate_panels',
    description: 'Navigate between panels',
  },
];
